units:
  kx: 19.05
  ky: 19.05
  px: 2
  py: 2
  step: 0
  # Shift ergogen output into Kicad drawing frame
  frame_shift_x: 140
  frame_shift_y: -160

points:
  key:
    footprints:
      mx_hotswap:
        type: mx
        params:
          hotswap: true
          reverse: false
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
  zones:
    matrix:
      anchor:
        shift: [frame_shift_x, frame_shift_y]
      columns:
        outer:
          key:
            # column_net: P19
        pinky:
          key:
            spread: kx
            stagger: 3
            # column_net: P18
        ring:
          key:
            spread: kx
            stagger: 5
            # column_net: P15
        middle:
          key:
            spread: kx
            stagger: 2
            # column_net: P14
        index:
          key:
            spread: kx
            stagger: -2
            # column_net: P16
        inner:
          key:
            spread: kx
            stagger: -3
            # column_net: P10
      rows:
        bottom:
          padding: ky
          # row_net: P8
        home:
          padding: ky
          # row_net: P7
        top:
          padding: ky
          # row_net: P6
        stretch:
          padding: ky
          # row_net: P5
    reach:
      anchor:
        ref: matrix_inner_home
        shift: [1kx + 0step, -0.5ky]
      columns:
        reach:
          key:
            # column_net: P10
            name: index_reach
      rows:
        reach:
          rotate: 0
          # row_net: P9
          key:
            name: reach
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-1.5kx, -1ky]
      columns:
        tucky1:
          key:
            spread: kx + step
            # column_net: P15
            name: thumb_tucky1
        tucky2:
          key:
            spread: kx + step
            # column_net: P14
            name: thumb_tucky2
        tucky3:
          key:
            stagger: -3
            spread: kx + step
            # column_net: P16
            name: thumb_tucky3
        reachy:
          key:
            width: 1.5kx
            origin: [0.15kx, -0.11ky]
            splay: -115
            # column_net: P10
            name: thumb_reachy
      rows:
        stretch:
          rotate: 0
          # row_net: P9
          key:
            name: thumb
  mirror:
    ref: matrix_pinky_home
    distance: 10 * kx + 5 * step + 1.5kx

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5, ky-0.5]
  shape_top_plate:
    # Left side
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_middle_stretch
          shift: [-1 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_middle_stretch
          shift: [3.5 kx + 1px, 0.5 ky + 0.5 py]
        - ref: index_reach
          shift: [0.5 kx + 1.25px, 0.5 ky + 0.5 py]
        - ref: index_reach
          shift: [0.5 kx + 1.15px, -1.15 ky + 0.75 py]
        - ref: thumb_reachy
          shift: [.7 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: thumb_tucky1
          shift: [2.6 kx - 0.5px, -0.5 ky - 1.75 py]
        - ref: thumb_tucky1
          shift: [-0.5 kx - 0.5px, -0.5 ky - 1.75 py]
        - ref: matrix_outer_bottom
          shift: [2 kx - 0.6 px, -0.5 ky - 0.5 py]
        - ref: matrix_outer_bottom
          shift: [-0.5 kx - 0.5 px, -0.5 ky - 0.5 py]

    # Right side (mirrored)
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_middle_stretch
          shift: [-1 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_middle_stretch
          shift: [3.5 kx + 1px, 0.5 ky + 0.5 py]
        - ref: mirror_index_reach
          shift: [0.5 kx + 1.25px, 0.5 ky + 0.5 py]
        - ref: mirror_index_reach
          shift: [0.5 kx + 1.15px, -1.15 ky + 0.75 py]
        - ref: mirror_thumb_reachy
          shift: [.7 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_thumb_tucky1
          shift: [2.6 kx - 0.5px, -0.5 ky - 1.75 py]
        - ref: mirror_thumb_tucky1
          shift: [-0.5 kx - 0.5px, -0.5 ky - 1.75 py]
        - ref: mirror_matrix_outer_bottom
          shift: [2 kx - 0.6 px, -0.5 ky - 0.5 py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5 kx - 0.5 px, -0.5 ky - 0.5 py]
  area_top_plate:
    - what: outline
      name: shape_top_plate
      fillet: 2
  combo:
    - name: area_top_plate
    - operation: subtract
      name: keys
pcbs:
  main:
    outlines:
      main:
        outline: shape_top_plate
    footprints:
      mx_1:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      # diode:
      #   what: diode
      #   where: true
      #   params:
      #     from: =colrow
      #     to: =row_net
      #   adjust:
      #     shift: [0, -5]
      # mcu:
      #   what: promicro
      #   params:
      #     orientation: "down"
      #   where:
      #     ref: matrix_inner_top
      #     shift: [0, 0]
      #     rotate: 0
