units:
  kx: 19.05
  ky: 19.05
  px: 1
  py: 1
  step: 0
  # Shift ergogen output into Kicad drawing frame
  frame_shift_x: 60
  frame_shift_y: -160

points:
  key:
    footprints:
      mx_hotswap:
        type: mx
        params:
          hotswap: true
          reverse: false
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
  zones:
    matrix:
      anchor:
        shift: [frame_shift_x, frame_shift_y]
      columns:
        outer:
          key:
            # column_net: P19
        pinky:
          key:
            spread: kx
            stagger: 3
            # column_net: P18
        ring:
          key:
            spread: kx
            stagger: 5
            # column_net: P15
        middle:
          key:
            spread: kx
            stagger: 2
            # column_net: P14
        index:
          key:
            spread: kx
            stagger: -2
            # column_net: P16
        inner:
          key:
            spread: kx
            stagger: -3
            # column_net: P10
      rows:
        bottom:
          padding: ky
          # row_net: P8
        home:
          padding: ky
          # row_net: P7
        top:
          padding: ky
          # row_net: P6
        stretch:
          padding: ky
          # row_net: P5
    reach:
      anchor:
        ref: matrix_inner_home
        shift: [1kx + 0step, -0.5ky]
      columns:
        reach:
          key:
            # column_net: P10
            name: index_reach
      rows:
        reach:
          rotate: 0
          # row_net: P9
          key:
            name: reach
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-1.5kx, -1ky]
      columns:
        tucky1:
          key:
            spread: kx + step
            # column_net: P15
            name: thumb_tucky1
        tucky2:
          key:
            spread: kx + step
            # column_net: P14
            name: thumb_tucky2
        tucky3:
          key:
            stagger: -3
            spread: kx + step
            # column_net: P16
            name: thumb_tucky3
        reachy:
          key:
            width: 1.5kx
            shift: [0.1kx, -0.295ky]
            splay: 65
            # column_net: P10
            name: thumb_reachy
      rows:
        stretch:
          rotate: 0
          # row_net: P9
          key:
            name: thumb
  mirror:
    ref: matrix_pinky_home
    distance: 13 * kx + 5 * step + 1.5kx

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5, ky-0.5]
  shape_top_plate:
    # Left side
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_outer_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_pinky_stretch
          shift: [-0.5 kx - 0.5px, .5 ky + 0.5 py]
        - ref: matrix_pinky_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_ring_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_ring_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_middle_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_middle_stretch
          shift: [0.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_index_stretch
          shift: [-.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_index_stretch
          shift: [.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_inner_stretch
          shift: [-.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: matrix_inner_stretch
          shift: [1.5 kx + 2px, 0.5 ky + 0.5 py]
        - ref: index_reach
          shift: [11.525, -20.345]
        - ref: thumb_reachy
          shift: [-0.75kx - 0.5px, -.5 ky - 0.5py]
        - ref: thumb_tucky3
          shift: [.5 kx + 0.49109px, -.5 ky - 0.5 py]
        - ref: thumb_tucky3
          shift: [-.5 kx - 0.5px, -.5 ky - .5 py]
        - ref: thumb_tucky2
          shift: [.5 kx - 0.5px, -.5 ky - .5 py]
        - ref: thumb_tucky1
          shift: [-.5 kx - .5px, -.5 ky - 0.5 py]
        - ref: matrix_outer_bottom
          shift: [2 kx - .5 px, -0.5 ky - 0.5 py]
        - ref: matrix_outer_bottom
          shift: [-0.5 kx - 0.5 px, -0.5 ky - 0.5 py]

    # Right side (mirrored, same as left)
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_outer_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_pinky_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_pinky_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_ring_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_ring_stretch
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_middle_stretch
          shift: [-0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_middle_stretch
          shift: [0.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_index_stretch
          shift: [-0.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_index_stretch
          shift: [0.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_inner_stretch
          shift: [-0.5 kx + 0.5px, 0.5 ky + 0.5 py]
        - ref: mirror_matrix_inner_stretch
          shift: [1.5 kx + 2px, 0.5 ky + 0.5 py]
        - ref: mirror_index_reach
          shift: [11.525, -20.345]
        - ref: mirror_thumb_reachy
          shift: [-0.75kx - 0.5px, -.5 ky - 0.5py]
        - ref: mirror_thumb_tucky3
          shift: [.5 kx + 0.49109px, -.5 ky - 0.5 py]
        - ref: mirror_thumb_tucky3
          shift: [-.5 kx - 0.5px, -.5 ky - .5 py]
        - ref: mirror_thumb_tucky2
          shift: [.5 kx - 0.5px, -.5 ky - .5 py]
        - ref: mirror_thumb_tucky1
          shift: [-.5 kx - .5px, -.5 ky - 0.5 py]
        - ref: mirror_matrix_outer_bottom
          shift: [2 kx - .5 px, -0.5 ky - 0.5 py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5 kx - 0.5 px, -0.5 ky - 0.5 py]
  area_top_plate:
    - what: outline
      name: shape_top_plate
      fillet: .5
  combo:
    - name: area_top_plate
    - operation: subtract
      name: keys
pcbs:
  main:
    outlines:
      main:
        outline: shape_top_plate
    footprints:
      mx:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      rgb_led:
        what: rgb
        where: true
        params:
          din: LED_DIN
          dout: LED_DOUT
        adjust:
          shift: [0, -5.08]
          rotate: 0
